### ISSUE TITLE
Unknown error uisng test data-set

### ISSUE THREAD

**Issue by kazumaxneo** [Bhattacharya-Lab/EquiPNAS#1]
Hello.

I want to use EquiPNAS to check my TF bing sites (picked up from RNA seq experiment).
 After creating the environment with conda, I downloaded the published models and tested the operation. 
However, anknown error occurred.
Is there any solution?
 
git clone https://github.com/Bhattacharya-Lab/EquiPNAS.git
cd EquiPNAS/
mamba env create -f EquiPNAS_env.yml
conda activate EquiPNAS
# Python version 3.10.4

$ python EquiPNAS.py --model_state_dict models/EquiPNAS-RNA/E-l12-768.pt --indir Preprocessing/ --outdir output/

********************************************************************************
*                            EquiPNAS                                          *
*           Improved protein-nucleic binding site prediction                   *
* using pretrained protein language model and equivariant deep graph learning  *
*         For comments, please email to dbhattacharya@vt.edu                   *
********************************************************************************

Residie-level predictions for each target is being saved at output//

Traceback (most recent call last):
  File "/home/kazu/Documents/EquiPNAS/EquiPNAS.py", line 155, in <module>
    main(PARS)
  File "/home/kazu/Documents/EquiPNAS/EquiPNAS.py", line 92, in main
    model.load_state_dict(torch.load(PARS.model_state_dict, map_location=device))
UnboundLocalError: local variable 'model' referenced before assignment
(EquiPNAS) kazu@kazu:~/Documents/EquiPNAS$

**Comment by rahmatullah-roche** [comment]
From your output error:

```
File "/home/kazu/Documents/EquiPNAS/EquiPNAS.py", line 92, in main
model.load_state_dict(torch.load(PARS.model_state_dict, map_location=device))

```
However, line 92 of EquiPNAS.py in the main function is:

`inference_loader = GraphDataLoader(dataset, batch_size=1, shuffle=False)`

which is different from what you reported. Have you changed `EquiPNAS.py`? If so, these changes might be causing the error. Please try using the original `EquiPNAS.py`.

Please closely follow the installation and usage instructions
